# This file controls the AWS CodeBuild

version: 0.2
phases:
  install:
    commands:
    - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
    - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
          
  pre_build:
    commands:
    - echo "Building Maven"
    - mvn clean install
    - echo "ECR Login"
    - aws --version
    - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
    - REPOSITORY_URI=508344954051.dkr.ecr.us-east-2.amazonaws.com/bloomkite-api-prod
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
    - docker --version
    - echo build block
    - docker build -t $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
            
  post_build:
    commands:
    - echo "Preparing war"
    - ls
    - cd target && ls  
    - cd ..
    - cp target/*.war ./app.war
    - ls
    - echo post build block
    - docker push $REPOSITORY_URI:latest
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - printf '[{"name":"bloomkite-api","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - app.war
    - imagedefinitions.json
  discard-paths: yes