DROP TABLE IF EXISTS `mailmessage`;
CREATE TABLE `mailmessage` (
	`mailMessageId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`to` VARCHAR(300) NULL DEFAULT NULL,
	`subject` VARCHAR(50) NULL DEFAULT NULL,
	`message` TEXT NULL DEFAULT NULL,
	`fromUser` VARCHAR(50) NULL DEFAULT NULL,
	`ifFailed` INT(1) NOT NULL DEFAULT '0',
	`noOfAttempt` INT(1) NOT NULL DEFAULT '0',
	`reason` VARCHAR(350) NULL DEFAULT NULL,
	PRIMARY KEY (`mailMessageId`)
);
